[smsdial]
; create and send a text message, expects number+message and
; connect to 17094009
exten => 200,1,SMS(${CALLERIDNUM},,${EXTEN},${CALLERIDNAME})
same => n,SMS(${CALLERIDNUM})
same => n,Hangup()